title: Abhishek Goyal
subtitle: Electronics and Computer Engineer
description: >- # this means to ignore newlines until "baseurl:"
  Motivated individual with strong work ethic and ability to work independently. Strong organizational and team collaboration skills with experience in improving processes.

url: "https://abhishek-g0yal.github.io" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "/fantastic-octo-winner" # the subpath of your site, e.g. /blog

# Edit these details

author_logo: profile.png
author: Abhishek Goyal
author_bio: Hi, my name is Abhishek Goyal. I built this site using devlopr-jekyll :D
author_email: "abhishek252167@gmail.com"
author_location: India
author_website_url: "https://abhishek_g0yal.github.io"
# typewrite-text: devlopr is a jekyll theme built for developers. You can edit this in _config.yml file

author_work_experiences:
            - company_name: Google
              company_logo: google.png
              company_url: https://google.com
              designation: Software Engineer
              description: Worked on various Google Products
              visibility: true
            - company_name: Microsoft
              company_logo: microsoft.png
              company_url: https://microsoft.com
              designation: Azure Developer
              description: Worked on various Azure Cloud Products
              visibility: true

author_education_details:
              - college_logo: mit.png
                college_name: MIT
                college_url: https://mit.org
                college_degree: CS Engineer
                description: Bachelor of Technology
                visibility: true

author_project_details:
              - project_thumbnail: gamershub.png
                project_title: Gamers Hub
                project_description: A Platform built for Gamers and Game Devs
                project_url: https://gamershub.in
                visibility: true
              - project_thumbnail: hack4r.PNG
                project_title: Hack4r
                project_description: A Platform built for Hackers and Penetration Testers
                project_url: https://hack4r.com
                visibility: true

# social links
twitter_username: abhishek_g0yal
github_username:  abhishek-g0yal
facebook_username: abhishek.g0yal
linkedin_username: abhishek-g0yal
behance_username: abhishek_g0yal
instagram_username: abhishek.g0yal
medium_username: abhishek_g0yal
telegram_username: abhishek_g0yal
dribbble_username: abhishek_g0yal
flickr_username: abhishek_g0yal


# wakatime username (coding activity)
wakatime_username: abhishek_g0yal

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true
